# Generated by Django 5.2 on 2026-04-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snipe_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=128)),
                ('category_type', models.CharField(max_length=128)),
                ('item_count', models.IntegerField(default=0)),
            ],
        ),
    ]
