# Generated by Django 5.2 on 2026-04-16 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options_categoryfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfield',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='inventory.category'),
        ),
    ]
