# Generated by Django 5.2 on 2025-05-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtthandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqtttopic',
            name='type',
            field=models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float')], max_length=10),
        ),
    ]
