# Generated by Django 5.2 on 2025-05-30 01:20

import django.db.models.deletion
import mqtthandler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtthandler', '0002_alter_mqtttopic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtttopic',
            name='broker',
            field=models.ForeignKey(default=mqtthandler.models.MQTTBroker.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='mqtthandler.mqttbroker'),
        ),
    ]
