# Generated by Django 5.2 on 2025-05-30 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtthandler', '0003_mqtttopic_broker'),
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtthandler.mqtttopic')),
            ],
        ),
    ]
