# Generated by Django 5.2 on 2025-05-30 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtthandler', '0004_mqttpageconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='mqtttopic',
            name='type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('str', 'String'), ('number', 'Number')], max_length=10),
        ),
        migrations.CreateModel(
            name='MQTTMessageFixed',
            fields=[
                ('mqttmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mqtthandler.mqttmessage')),
                ('value', models.CharField(max_length=250)),
            ],
            bases=('mqtthandler.mqttmessage',),
        ),
        migrations.CreateModel(
            name='MQTTMessageNumber',
            fields=[
                ('mqttmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mqtthandler.mqttmessage')),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
            ],
            bases=('mqtthandler.mqttmessage',),
        ),
    ]
