# Generated by Django 5.2 on 2025-05-30 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtthandler', '0006_remove_mqttmessagefixed_mqttmessage_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mqtttopic',
            name='type',
        ),
    ]
