# Generated by Django 5.2 on 2025-05-30 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtthandler', '0007_remove_mqtttopic_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mqttpageconfig',
            name='topics',
        ),
        migrations.CreateModel(
            name='MQTTUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.ManyToManyField(to='mqtthandler.mqtttopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mqttpageconfig',
            name='topics',
            field=models.ManyToManyField(to='mqtthandler.mqtttopic'),
        ),
    ]
