# Generated by Django 5.2 on 2026-09-04 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ip_address', models.CharField(max_length=32)),
                ('mac_address', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='player.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='current_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_config', to='player.playerconfig'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=128)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('frame_rate', models.FloatField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, max_length=128, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='player.player')),
            ],
        ),
        migrations.AddField(
            model_name='playerconfig',
            name='screen1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video1', to='player.video'),
        ),
        migrations.AddField(
            model_name='playerconfig',
            name='screen2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video2', to='player.video'),
        ),
    ]
