# Generated by Django 5.2 on 2026-09-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_player_name_alter_video_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('players', models.ManyToManyField(related_name='syncgroup', to='player.player')),
            ],
        ),
    ]
